name: SonarCloud
on:
  push:
    branches:
      - develop
  pull_request:
    types: [opened, synchronize, reopened]
jobs:
  build:
    name: Build and analyze
    runs-on: windows-latest
    steps:
      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 1.11
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0  # Shallow clones should be disabled for a better relevancy of analysis
      - name: Cache lib obj
        uses: actions/cache@v1
        with:
          path: ~\SWCRunesLib\obj
          key: ${{ runner.os }}-LibObj
          restore-keys: ${{ runner.os }}-LibObj
      - name: Cache main obj
        uses: actions/cache@v1
        with:
          path: ~\SWCRunes\obj
          key: ${{ runner.os }}-Obj
          restore-keys: ${{ runner.os }}-Obj
      - name: Cache SonarCloud packages
        uses: actions/cache@v1
        with:
          path: ~\sonar\cache
          key: ${{ runner.os }}-sonar
          restore-keys: ${{ runner.os }}-sonar
      - name: Cache SonarCloud scanner
        id: cache-sonar-scanner
        uses: actions/cache@v1
        with:
          path: .\.sonar\scanner
          key: ${{ runner.os }}-sonar-scanner
          restore-keys: ${{ runner.os }}-sonar-scanner
      - name: Install SonarCloud scanner
        if: steps.cache-sonar-scanner.outputs.cache-hit != 'true'
        shell: powershell
        run: |
          New-Item -Path .\.sonar\scanner -ItemType Directory
          dotnet tool update dotnet-sonarscanner --tool-path .\.sonar\scanner
      - name: Install MAUI workload
        run: dotnet workload install maui 
      - name: Build and analyze
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # Needed to get PR information, if any
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        shell: powershell
        run: |
          .\.sonar\scanner\dotnet-sonarscanner begin /k:"scorduan_swcrunes" /o:"scorduan" /d:sonar.login="${{ secrets.SONAR_TOKEN }}" /d:sonar.host.url="https://sonarcloud.io"
          dotnet build
          .\.sonar\scanner\dotnet-sonarscanner end /d:sonar.login="${{ secrets.SONAR_TOKEN }}"
      - name: Test
        run: dotnet test --no-build --verbosity normal
      - name: Upload Windows Artifact
        uses: actions/upload-artifact@v2.3.1
        with:
          name: windows-ci-build
          path: src/SWCrunes/bin/Release/net7.0-windows*/**/SWCRunes*.msix
      - name: Upload Windows Artifact (Debug)
        uses: actions/upload-artifact@v2.3.1
        with:
          name: windows-ci-build
          path: src/SWCrunes/bin/Debug/net7.0-windows*/**/SWCRunes*.msix
      - name: Upload Mac Artifact
        uses: actions/upload-artifact@v2.3.1
        with:
          name: mac-ci-build
          path: src/SWCrunesbin/Release/net7.0-maccatalyst*/**/SWCRunes*.app
      - name: Upload Mac Artifact (Debug)
        uses: actions/upload-artifact@v2.3.1
        with:
          name: mac-ci-build
          path: src/SWCrunesbin/Debug/net7.0-maccatalyst*/**/SWCRunes*.app
          
          
          
